export { AuthService } from "./auth/auth.service";
export { AuthGuard } from "./auth/auth-guard.service";
export { BaseRestService } from "./base-service/base-rest.service";
export { BaseCommunicateService } from "./base-service/base-communicate.service";
export { DialogsService } from "./dialog/dialogs.service";
export { ValidationService } from "./validation/validation.service";
export { ClassificationMaterialService, ClassificationMaterialServiceCommunicate } from "./classification-material/classification-material.service";
// export { EmployeeService } from "./employee/employee.service";
export { GradeMaterialService } from "./grade-material/grade-material.service";
export { JobCardDetailService, JobCardDetailServiceServiceCommunicate } from "./jobcard-detail/jobcard-detail.service";
export { JobCardMasterService, JobCardMasterServiceCommunicate } from "./jobcard-master/jobcard-master.service";
export { MachineService, MachineServiceCommunicate } from "./machine/machine.service";
export { MachineHasOperatorService, MachineHasOperatorServiceCommunicate } from "./machine-has-operator/machine-has-operator.service";
export { MaterialService, MaterialServiceCommunicate } from "./material/material.service";
// export { ProjectCodeDetailService } from "./projectcode-detail/projectcode-detail.service";
// export { ProjectCodeMasterService, ProjectCodeMasterServiceCommunicate } from "./projectcode-master/projectcode-master.service";
export { PropertyMachineService, PropertyMachineServiceCommunicate } from "./property-machine/property-machine.service";
export { TaskMachineService, TaskMachineServiceCommunicate } from "./task-machine/task-machine.service";
export { TypeMachineService, TypeMachineServiceCommunicate } from "./type-machine/type-machine.service";
export { TypeStandardTimeService, TypeStandardTimeServiceCommunicate } from "./type-standard-time/type-standard-time.service";
export { UnitMeasureService, UnitMeasureServiceCommunicate } from "./units-measure/units-measure.service";
export { CuttingPlanService, CuttingPlanServiceCommunicate } from "./cutting-plan/cutting-plan.service";
export { TemplateProjectDetailService, TemplateProjectDetailServiceCommunicate } from "./template-project-detail/template-project-detail.service";
export { DataTableServiceCommunicate } from "./data-table/data-table.service";
export { UserService } from "./user/user.service";
export { EmployeeGroupService } from "./employee-group/employee-group.service";
export { OverTimeMasterService, OverTimeMasterServiceCommunicate } from "./overtime-master/overtime-master.service";
export { OverTimeDetailService } from "./overtime-detail/overtime-detail.service";